<!--
    Created by wangyang on 2019-05-24.
    itwangyang@gmail.com
    http://www.itwangyang.xyz
-->
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0">
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black">
  <meta name="format-detection" content="telephone=no">
  <title>Title</title>
  <meta name="description" content="">
  <meta name="keywords" content="">
  <!--所有的IE都起作用：-->
  <!--[if IE]>  <link rel="stylesheet" type="text/css" href="all-ie-only.css/> <![endif]-->

</head>
<body>



<script>
  function q() {
    return new Promise((resolve,reject) => {
      setTimeout(()=>{
        reject("成功");
      },1000)
    })
  }



  (async function () {
    try{
      let res = await q();
      console.log(res);
    }catch (e) {
      console.log(e);
    }

  })()



  /*

  await可以执行异步操作，但是await必须在async函数内执行

  await操作可以有返回值，这个返回值表示promise操作成功的返回值

  如果await里面执行的异步操作发生了reject，或者发生了错误，那么只能使用try...catch语法来进行错误处理

   */
</script>
</body>
</html>